-- ============================================================
-- CABINETRY DESIGNER TABLES
-- All prefixed with cd_ to avoid collision with existing tables.
-- Shares the same Supabase project as ff-job-schedule-v1.
-- Uses existing teams / team_members / auth.users tables.
-- ============================================================

-- Team-level default parameters for cabinetry
CREATE TABLE IF NOT EXISTS cd_team_defaults (
  team_id         UUID PRIMARY KEY REFERENCES teams(team_id) ON DELETE CASCADE,
  default_params  JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Projects
CREATE TABLE IF NOT EXISTS cd_projects (
  project_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id         UUID NOT NULL REFERENCES teams(team_id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  client_name     TEXT,
  address         TEXT,
  default_params  JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by      UUID REFERENCES auth.users(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cd_projects_team ON cd_projects(team_id);

-- Rooms
CREATE TABLE IF NOT EXISTS cd_rooms (
  room_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id      BIGINT NOT NULL REFERENCES cd_projects(project_id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  floor_to_ceiling NUMERIC,
  default_params  JSONB NOT NULL DEFAULT '{}'::jsonb,
  sort_order      INT NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cd_rooms_project ON cd_rooms(project_id);

-- Walls (ordered line segments per room)
CREATE TABLE IF NOT EXISTS cd_walls (
  wall_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id         BIGINT NOT NULL REFERENCES cd_rooms(room_id) ON DELETE CASCADE,
  x1              NUMERIC NOT NULL,
  y1              NUMERIC NOT NULL,
  x2              NUMERIC NOT NULL,
  y2              NUMERIC NOT NULL,
  thickness       NUMERIC NOT NULL DEFAULT 4.5,
  height          NUMERIC,
  sort_order      INT NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cd_walls_room ON cd_walls(room_id);

-- Placed objects (cabinets, appliances, fillers, etc.)
CREATE TABLE IF NOT EXISTS cd_placed_objects (
  object_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id         BIGINT NOT NULL REFERENCES cd_rooms(room_id) ON DELETE CASCADE,
  wall_id         BIGINT REFERENCES cd_walls(wall_id) ON DELETE SET NULL,
  object_type     TEXT NOT NULL,
  catalog_id      TEXT,
  x               NUMERIC NOT NULL DEFAULT 0,
  y               NUMERIC NOT NULL DEFAULT 0,
  z               NUMERIC NOT NULL DEFAULT 0,
  rotation        NUMERIC NOT NULL DEFAULT 0,
  width           NUMERIC,
  height          NUMERIC,
  depth           NUMERIC,
  params          JSONB NOT NULL DEFAULT '{}'::jsonb,
  sort_order      INT NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cd_placed_objects_room ON cd_placed_objects(room_id);
CREATE INDEX IF NOT EXISTS idx_cd_placed_objects_wall ON cd_placed_objects(wall_id);

-- Cabinet face definitions (doors/drawers per placed object)
CREATE TABLE IF NOT EXISTS cd_cabinet_faces (
  face_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_id       BIGINT NOT NULL REFERENCES cd_placed_objects(object_id) ON DELETE CASCADE,
  face_type       TEXT NOT NULL,
  width           NUMERIC,
  height          NUMERIC,
  hinge_side      TEXT,
  row_index       INT NOT NULL DEFAULT 0,
  col_index       INT NOT NULL DEFAULT 0,
  params          JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cd_cabinet_faces_object ON cd_cabinet_faces(object_id);

-- Snapshots of generated outputs (DXF + reports)
CREATE TABLE IF NOT EXISTS cd_generations (
  generation_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id         BIGINT NOT NULL REFERENCES cd_rooms(room_id) ON DELETE CASCADE,
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  input_hash      TEXT NOT NULL,
  dxf_url         TEXT,
  reports         JSONB,
  status          TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'complete', 'error'))
);

CREATE INDEX IF NOT EXISTS idx_cd_generations_room ON cd_generations(room_id);
CREATE INDEX IF NOT EXISTS idx_cd_generations_hash ON cd_generations(room_id, input_hash);

-- ============================================================
-- ROW LEVEL SECURITY
-- Backend uses service-role key (bypasses RLS), but these
-- policies protect against direct Supabase client access.
-- Pattern: team members can access their team's data.
-- ============================================================

ALTER TABLE cd_team_defaults ENABLE ROW LEVEL SECURITY;
ALTER TABLE cd_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE cd_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE cd_walls ENABLE ROW LEVEL SECURITY;
ALTER TABLE cd_placed_objects ENABLE ROW LEVEL SECURITY;
ALTER TABLE cd_cabinet_faces ENABLE ROW LEVEL SECURITY;
ALTER TABLE cd_generations ENABLE ROW LEVEL SECURITY;

-- Helper: check if current user belongs to a given team
CREATE OR REPLACE FUNCTION cd_user_in_team(p_team_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM team_members
    WHERE team_id = p_team_id
      AND user_id = auth.uid()
  );
$$;

-- cd_team_defaults: team members can read/write their own team defaults
CREATE POLICY cd_team_defaults_select ON cd_team_defaults
  FOR SELECT USING (cd_user_in_team(team_id));
CREATE POLICY cd_team_defaults_insert ON cd_team_defaults
  FOR INSERT WITH CHECK (cd_user_in_team(team_id));
CREATE POLICY cd_team_defaults_update ON cd_team_defaults
  FOR UPDATE USING (cd_user_in_team(team_id));

-- cd_projects: team members can CRUD their team's projects
CREATE POLICY cd_projects_select ON cd_projects
  FOR SELECT USING (cd_user_in_team(team_id));
CREATE POLICY cd_projects_insert ON cd_projects
  FOR INSERT WITH CHECK (cd_user_in_team(team_id));
CREATE POLICY cd_projects_update ON cd_projects
  FOR UPDATE USING (cd_user_in_team(team_id));
CREATE POLICY cd_projects_delete ON cd_projects
  FOR DELETE USING (cd_user_in_team(team_id));

-- cd_rooms: access via project's team
CREATE POLICY cd_rooms_select ON cd_rooms
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM cd_projects p WHERE p.project_id = cd_rooms.project_id AND cd_user_in_team(p.team_id))
  );
CREATE POLICY cd_rooms_insert ON cd_rooms
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM cd_projects p WHERE p.project_id = cd_rooms.project_id AND cd_user_in_team(p.team_id))
  );
CREATE POLICY cd_rooms_update ON cd_rooms
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM cd_projects p WHERE p.project_id = cd_rooms.project_id AND cd_user_in_team(p.team_id))
  );
CREATE POLICY cd_rooms_delete ON cd_rooms
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM cd_projects p WHERE p.project_id = cd_rooms.project_id AND cd_user_in_team(p.team_id))
  );

-- cd_walls: access via room → project → team
CREATE POLICY cd_walls_select ON cd_walls
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_walls.room_id AND cd_user_in_team(p.team_id)
    )
  );
CREATE POLICY cd_walls_insert ON cd_walls
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_walls.room_id AND cd_user_in_team(p.team_id)
    )
  );
CREATE POLICY cd_walls_update ON cd_walls
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_walls.room_id AND cd_user_in_team(p.team_id)
    )
  );
CREATE POLICY cd_walls_delete ON cd_walls
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_walls.room_id AND cd_user_in_team(p.team_id)
    )
  );

-- cd_placed_objects: access via room → project → team
CREATE POLICY cd_placed_objects_select ON cd_placed_objects
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_placed_objects.room_id AND cd_user_in_team(p.team_id)
    )
  );
CREATE POLICY cd_placed_objects_insert ON cd_placed_objects
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_placed_objects.room_id AND cd_user_in_team(p.team_id)
    )
  );
CREATE POLICY cd_placed_objects_update ON cd_placed_objects
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_placed_objects.room_id AND cd_user_in_team(p.team_id)
    )
  );
CREATE POLICY cd_placed_objects_delete ON cd_placed_objects
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_placed_objects.room_id AND cd_user_in_team(p.team_id)
    )
  );

-- cd_cabinet_faces: access via object → room → project → team
CREATE POLICY cd_cabinet_faces_select ON cd_cabinet_faces
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM cd_placed_objects o
      JOIN cd_rooms r ON r.room_id = o.room_id
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE o.object_id = cd_cabinet_faces.object_id AND cd_user_in_team(p.team_id)
    )
  );
CREATE POLICY cd_cabinet_faces_insert ON cd_cabinet_faces
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM cd_placed_objects o
      JOIN cd_rooms r ON r.room_id = o.room_id
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE o.object_id = cd_cabinet_faces.object_id AND cd_user_in_team(p.team_id)
    )
  );
CREATE POLICY cd_cabinet_faces_delete ON cd_cabinet_faces
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM cd_placed_objects o
      JOIN cd_rooms r ON r.room_id = o.room_id
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE o.object_id = cd_cabinet_faces.object_id AND cd_user_in_team(p.team_id)
    )
  );

-- cd_generations: access via room → project → team
CREATE POLICY cd_generations_select ON cd_generations
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_generations.room_id AND cd_user_in_team(p.team_id)
    )
  );
CREATE POLICY cd_generations_insert ON cd_generations
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM cd_rooms r
      JOIN cd_projects p ON p.project_id = r.project_id
      WHERE r.room_id = cd_generations.room_id AND cd_user_in_team(p.team_id)
    )
  );

-- ============================================================
-- UPDATED_AT TRIGGER (reuse pattern from existing tables)
-- ============================================================

CREATE OR REPLACE FUNCTION cd_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER cd_team_defaults_updated_at
  BEFORE UPDATE ON cd_team_defaults
  FOR EACH ROW EXECUTE FUNCTION cd_set_updated_at();

CREATE TRIGGER cd_projects_updated_at
  BEFORE UPDATE ON cd_projects
  FOR EACH ROW EXECUTE FUNCTION cd_set_updated_at();

CREATE TRIGGER cd_rooms_updated_at
  BEFORE UPDATE ON cd_rooms
  FOR EACH ROW EXECUTE FUNCTION cd_set_updated_at();

CREATE TRIGGER cd_walls_updated_at
  BEFORE UPDATE ON cd_walls
  FOR EACH ROW EXECUTE FUNCTION cd_set_updated_at();

CREATE TRIGGER cd_placed_objects_updated_at
  BEFORE UPDATE ON cd_placed_objects
  FOR EACH ROW EXECUTE FUNCTION cd_set_updated_at();
